// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package data

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message
type ContactRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	MobileNumber         string   `protobuf:"bytes,3,opt,name=mobile_number,json=mobileNumber,proto3" json:"mobile_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContactRequest) Reset()         { *m = ContactRequest{} }
func (m *ContactRequest) String() string { return proto.CompactTextString(m) }
func (*ContactRequest) ProtoMessage()    {}
func (*ContactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0}
}

func (m *ContactRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactRequest.Unmarshal(m, b)
}
func (m *ContactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactRequest.Marshal(b, m, deterministic)
}
func (m *ContactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactRequest.Merge(m, src)
}
func (m *ContactRequest) XXX_Size() int {
	return xxx_messageInfo_ContactRequest.Size(m)
}
func (m *ContactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ContactRequest proto.InternalMessageInfo

func (m *ContactRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ContactRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ContactRequest) GetMobileNumber() string {
	if m != nil {
		return m.MobileNumber
	}
	return ""
}

// The response message
type ContactSummary struct {
	Summary              string   `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContactSummary) Reset()         { *m = ContactSummary{} }
func (m *ContactSummary) String() string { return proto.CompactTextString(m) }
func (*ContactSummary) ProtoMessage()    {}
func (*ContactSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{1}
}

func (m *ContactSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactSummary.Unmarshal(m, b)
}
func (m *ContactSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactSummary.Marshal(b, m, deterministic)
}
func (m *ContactSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactSummary.Merge(m, src)
}
func (m *ContactSummary) XXX_Size() int {
	return xxx_messageInfo_ContactSummary.Size(m)
}
func (m *ContactSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactSummary.DiscardUnknown(m)
}

var xxx_messageInfo_ContactSummary proto.InternalMessageInfo

func (m *ContactSummary) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func init() {
	proto.RegisterType((*ContactRequest)(nil), "data.ContactRequest")
	proto.RegisterType((*ContactSummary)(nil), "data.ContactSummary")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor_871986018790d2fd) }

var fileDescriptor_871986018790d2fd = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x49, 0x2c, 0x49,
	0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0xe2, 0xb9, 0xf8, 0x9c, 0xf3,
	0xf3, 0x4a, 0x12, 0x93, 0x4b, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x84, 0xb8, 0x58,
	0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x21, 0x11, 0x2e,
	0xd6, 0xd4, 0xdc, 0xc4, 0xcc, 0x1c, 0x09, 0x26, 0xb0, 0x20, 0x84, 0x23, 0xa4, 0xcc, 0xc5, 0x9b,
	0x9b, 0x9f, 0x94, 0x99, 0x93, 0x1a, 0x9f, 0x57, 0x9a, 0x9b, 0x94, 0x5a, 0x24, 0xc1, 0x0c, 0x96,
	0xe5, 0x81, 0x08, 0xfa, 0x81, 0xc5, 0x94, 0xb4, 0xe0, 0x16, 0x04, 0x97, 0xe6, 0xe6, 0x26, 0x16,
	0x55, 0x0a, 0x49, 0x70, 0xb1, 0x17, 0x43, 0x98, 0x50, 0x3b, 0x60, 0x5c, 0x23, 0x2f, 0x2e, 0x2e,
	0x97, 0xc4, 0x92, 0xc4, 0xe0, 0x92, 0xa2, 0xd4, 0xc4, 0x5c, 0x21, 0x1b, 0x2e, 0x2e, 0x08, 0x0b,
	0x24, 0x26, 0x24, 0xa2, 0x07, 0x76, 0x3b, 0xaa, 0x63, 0xa5, 0x50, 0x45, 0xa1, 0x36, 0x28, 0x31,
	0x68, 0x30, 0x26, 0xb1, 0x81, 0x7d, 0x69, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xb7, 0xac, 0xb6,
	0x5a, 0xf3, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DataStreamClient is the client API for DataStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataStreamClient interface {
	StreamData(ctx context.Context, opts ...grpc.CallOption) (DataStream_StreamDataClient, error)
}

type dataStreamClient struct {
	cc *grpc.ClientConn
}

func NewDataStreamClient(cc *grpc.ClientConn) DataStreamClient {
	return &dataStreamClient{cc}
}

func (c *dataStreamClient) StreamData(ctx context.Context, opts ...grpc.CallOption) (DataStream_StreamDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DataStream_serviceDesc.Streams[0], "/data.DataStream/StreamData", opts...)
	if err != nil {
		return nil, err
	}
	x := &dataStreamStreamDataClient{stream}
	return x, nil
}

type DataStream_StreamDataClient interface {
	Send(*ContactRequest) error
	CloseAndRecv() (*ContactSummary, error)
	grpc.ClientStream
}

type dataStreamStreamDataClient struct {
	grpc.ClientStream
}

func (x *dataStreamStreamDataClient) Send(m *ContactRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dataStreamStreamDataClient) CloseAndRecv() (*ContactSummary, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ContactSummary)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DataStreamServer is the server API for DataStream service.
type DataStreamServer interface {
	StreamData(DataStream_StreamDataServer) error
}

func RegisterDataStreamServer(s *grpc.Server, srv DataStreamServer) {
	s.RegisterService(&_DataStream_serviceDesc, srv)
}

func _DataStream_StreamData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataStreamServer).StreamData(&dataStreamStreamDataServer{stream})
}

type DataStream_StreamDataServer interface {
	SendAndClose(*ContactSummary) error
	Recv() (*ContactRequest, error)
	grpc.ServerStream
}

type dataStreamStreamDataServer struct {
	grpc.ServerStream
}

func (x *dataStreamStreamDataServer) SendAndClose(m *ContactSummary) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dataStreamStreamDataServer) Recv() (*ContactRequest, error) {
	m := new(ContactRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _DataStream_serviceDesc = grpc.ServiceDesc{
	ServiceName: "data.DataStream",
	HandlerType: (*DataStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamData",
			Handler:       _DataStream_StreamData_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "data.proto",
}
